'use strict';

// Declare app level module which depends on views, and components
angular.module('myApp', [
    'ngRoute',
    'ui.bootstrap',
    'restangular',
    'myApp.pictures',
    'myApp.shop',
    'myApp.cart',
    'myApp.version'
]).config(function ($locationProvider, $routeProvider, RestangularProvider) {
    $locationProvider.hashPrefix('!');

    $routeProvider.otherwise({redirectTo: '/pictures'});

    RestangularProvider.setBaseUrl('http://localhost:9998/')

});
